const dontenv=require('dotenv')
dontenv.config()
const express=require('express')
const app=express()
const cors=require('cors')
const dbconnection=require('./db/db.js')
const cookieparser=require('cookie-parser')
const authrouter=require('./routes/user.route.js')
const captionrouter=require("./routes/caption.routes.js")
const senddetailsrouter=require("./routes/senddeatils.route.js")
app.use(cors())
app.use(express.json())
app.use(express.urlencoded({extended:true}))
app.use(cookieparser())
dbconnection()
app.use('/api/senddetails',senddetailsrouter)
app.use('/api/user',authrouter)
app.use('/api/caption',captionrouter)
app.get('/',(req,res)=>{
    res.send('hello world')
})
module.exports=app;